sudo: required
services:
  - docker

before_install:
  - docker build -t elvinpedro/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run elvinpedro/react-test npm test -- -- coverage

after_success:
  - docker build -t elvinpedro/multi-client ./client
  - docker build -t elvinpedro/multi-nginx ./nginx
  - docker build -t elvinpedro/multi-server ./server
  - docker build -t elvinpedro/multi-worker ./worker